Repository suzuki-shunsuke/pinact, pull requests merged in 2025-03, with the labels that each got.

#786 docs: update
  INSTALL.md
Labels: documentation

#798 feat: support regular expressions to ignore actions
  .github/workflows/wc-test.yaml
  .pinact.yaml
  README.md
  json-schema/pinact.json
  pkg/controller/run/config.go
  pkg/controller/run/parse_line.go
  testdata/foo.yaml
  testdata/foo.yaml.after
Labels: enhancement

#805 feat: look for action.yaml and action.yml by default
  .github/workflows/wc-test.yaml
  .pinact.yaml
  pkg/controller/run/list_workflows.go
  testdata/actions.after/action.yaml
  testdata/actions.after/action.yml
  testdata/actions.after/foo/action.yaml
  testdata/actions.after/foo/action.yml
  testdata/actions.after/foo/bar/action.yaml
  testdata/actions.after/foo/bar/action.yml
  testdata/actions/action.yaml
  testdata/actions/action.yml
  testdata/actions/foo/action.yaml
  testdata/actions/foo/action.yml
  testdata/actions/foo/bar/action.yaml
  testdata/actions/foo/bar/action.yml
Labels: enhancement

#813 docs: fix the default target files
  README.md
Labels: documentation

#814 docs: update
  README.md
Labels: documentation

#818 feat: support versions like vX.Y
  pkg/controller/run/parse_line.go
  testdata/foo.yaml
  testdata/foo.yaml.after
Labels: enhancement

#823 Make `pinact run` fail if it can't pin some actions
  pkg/controller/run/controller.go
  pkg/controller/run/parse_line.go
  pkg/controller/run/parse_line_internal_test.go
  pkg/controller/run/run.go
  pkg/controller/run/search_file.go
  testdata/foo.yaml
  testdata/foo.yaml.after
Labels: enhancement, breaking change

#833 fix(windows): path pattern not matched on Windows
  pkg/controller/run/search_file.go
Labels: bug

#834 fix: output warning instead of returning error when a long tag isn't found
  pkg/controller/run/parse_line.go
  pkg/controller/run/parse_line_internal_test.go
Labels: bug

#840 feat: Add `ignore_actions[].ref` in config
  .pinact.yaml
  README.md
  json-schema/pinact.json
  pkg/controller/run/config.go
  pkg/controller/run/config_test.go
  pkg/controller/run/parse_line.go
Labels: enhancement

#845 docs: Make example config stricter
  README.md
Labels: documentation

#854 docs: update
  USAGE.md
  aqua/aqua-checksums.json
  aqua/imports/pinact.yaml
Labels: documentation

#860 Fix a bug that `pinact run --check` fixes files
  .github/workflows/wc-test.yaml
  pkg/config/config.go
  pkg/controller/run/parse_line.go
  pkg/controller/run/run.go
Labels: bug

#855 Change the default schema version to `3` and abandon the version `2`
  docs/schema_v2.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/run/run.go
  pkg/controller/run/search_file.go
Labels: breaking change
