Repository suzuki-shunsuke/pinact, pull requests merged in 2025-05, with the labels that each got.

#945 docs: add Contributing and pull request template
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#946 docs: update contributing
  CONTRIBUTING.md
Labels: documentation

#948 docs: fix
  CONTRIBUTING.md
Labels: documentation

#952 Support reading GitHub Access token from keyring
  README.md
  go.mod
  go.sum
  pkg/cli/initcmd/command.go
  pkg/cli/run/command.go
  pkg/cli/runner.go
  pkg/cli/token/command.go
  pkg/controller/rmtoken/controller.go
  pkg/controller/rmtoken/rm.go
  pkg/controller/settoken/controller.go
  pkg/controller/settoken/set.go
  pkg/github/github.go
  pkg/github/keyring.go
Labels: enhancement

#968 fix: fix version command
  go.mod
  go.sum
Labels: bug

#970 Fix typo: `tokn` -> `token`
  README.md
Labels: documentation
